pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'hearthwind-custom'

include 'hearthwind-survival'
include 'hearthwind-skills'
include 'hearthwind-primitive'
include 'hearthwind-world'
include 'hearthwind-jobs'
include 'hearthwind-client'
include 'villagesandpillages'
include 'smallships'
include 'letsdo-farm-and-charm'
include 'letsdo-bakery'
include 'letsdo-vinery'
include 'letsdo-brewery'
include 'letsdo-herbalbrews'
include 'letsdo-candlelight'
include 'letsdo-meadow'
include 'letsdo-nethervinery'
include 'athena'
include 'chipped'
include 'passable-foliage'
include 'exposure'
	include 'dungeonz'
include 'logbegone'
include 'entitycollisionfpsfix'
include 'pockets'
include 'couplings'
include 'memoryleakfix'
include 'async-locator'
include 'lavender'
	include 'profundis'
	include 'fleshz'
	include 'adventurez'
	// include 'surveyor' // TEMP-OFF 2026-09-21: 26.1->26.2 nudge WIP (~324 compile errors); re-enable when :surveyor:compileJava is green
	// NOTE: letsdo-brewery/candlelight/herbalbrews/meadow sources are present
