pluginManagement {
	repositories {
		maven {
			name = 'Fabric'
			url = 'https://maven.fabricmc.net/'
		}
		mavenCentral()
		gradlePluginPortal()
	}
}

rootProject.name = 'hearthwind-custom'

include 'hearthwind-survival'
include 'hearthwind-skills'
include 'hearthwind-primitive'
include 'hearthwind-world'
include 'hearthwind-jobs'
